### ISSUE TITLE
Add flag to force FREB collection

### ISSUE THREAD

**Issue by bmf-ribeiro** [NL-Cristi/LogCatcher#16]
Given that the amount of generated FREBS is limited, sometimes we disable Failed Request Tracing as soon as the issue we are trying to analyze happens in order for it to not be overwritten.

In those scenarios, when we run LogCatcher since they are disabled for the selected websites they are not automatically collected, and have to be zipped and collected separately.

For those scenarios it would be useful to have a flag to force FREB collection regardless of it being enabled or not for any given site.

As far as can see it could have two approaches:
1.  `-ForceFrebCollection $true` and ignore whether the flag is set or not at the site level and try to collect
2. `-FrebCollectionSiteIds 2,3` and specify for which sites we want to ignore the flag, as for customers with large installations there could be  a large overhead in trying to collect for all of them.

**Comment by NL-Cristi** [comment]
closed as solved by #23
