### ISSUE TITLE
HttpERR logs do not respect the MaxDays parameter

### ISSUE THREAD

**Issue by bmf-ribeiro** [NL-Cristi/LogCatcher#17]
The collection of the HttpERR logs is not respecting the Logs Age parameter, which can lead to gigabytes of files being collected in older servers which can severely slow down the process.

Looking at the code for the http error logs operation

https://github.com/cristian-clamsen/LogCatcher/blob/96ab07cffb25f8efdcfca384e2d1679cad85b4ee/LogCatcher/General/CatchFilteredIISzip.ps1#L41-L45

I would assume that a quick fix would be to add the `/maxage:$MaxDay` similar to the operation bellow that catches the iis logs

https://github.com/cristian-clamsen/LogCatcher/blob/96ab07cffb25f8efdcfca384e2d1679cad85b4ee/LogCatcher/General/CatchFilteredIISzip.ps1#L33-L37

If you would like let me know, and I can test it and open a PR

**Comment by NL-Cristi** [comment]
added change  [                   Robocopy.exe $FilteredLogDefinition.Location $httperr /s /maxage:$MaxDays | Out-Null](https://github.com/cristian-clamsen/LogCatcher/blob/0437e9e0dc082ff502ee15a776e0f0c6860acb92/LogCatcher/General/CatchFilteredIISzip.ps1#L44)
